// 添加控制器
        app.controller('fans',function($scope){
            $scope.fansarr=[
                {'head':'images/a1.jpg','name':'小王','job':'设计师，博客','star':25},
                {'head':'images/a2.jpg','name':'张琳','job':'作家，杂志编辑','star':47},
                {'head':'images/a3.jpg','name':'李小明','job':'艺术总监，电影剪辑','star':10},
                {'head':'images/a4.jpg','name':'赵大程','job':'音乐家，运动员','star':66}
                ];
        })
        app.controller('nav',function($scope){
            $scope.navarr=[
                {'title':'首页','icon':'glyphicon-home','childnav':''},
                {'title':'简介','icon':'glyphicon-file','childnav':''},
                {'title':'信息','icon':'glyphicon-envelope','childnav':''},
                {'title':'操作','icon':'glyphicon-cog','childnav':['设置栏目','更多设置','分割线']}
                ];
        })
        app.controller('m_nav',function($scope){
            $scope.m_navarr=[
                {'m_title':'最新动态','m_link':'/'},
                {'m_title':'简介','m_link':'/introduction'},
                {'m_title':'消息','m_link':'/message'}
            ];
        })
        app.controller('commentController',function($scope){
            $scope.comment={text:''};
        })
        app.controller('ccController',function($scope){
            $scope.comment=[
                {'author':'','time':'','text':'','reply':''},
            ];
        })